### ISSUE TITLE
How to log in?

### ISSUE THREAD

**Issue by andrewMuntyan** [svendahlstrand/ica-api#10]
Hi!

I found this repo yesterday. Have a question.
How can i log in and get authorization token? 
Is it possible to get delivery time slots trough this api? 

Thanks in advance!

**Comment by svendahlstrand** [comment]
Hello!

> How can i log in and get authorization token?

The steps to log in is described in the [README.md](https://github.com/svendahlstrand/ica-api/blob/master/README.md) file. It's in Swedish, though, and if that's not your thing you'll have to use Google Translate or a similar service. ☺️ It tried that just now and it does a decent job with the translation.

You have to have a membership with ICA, called "Stammis". You can [apply on their website](https://www.ica.se/stammis-pa-ica/bli-stammis-pa-ica/) or get help in one of their stores.

> Is it possible to get delivery time slots trough this api?

Is that a feature in their smartphone app? If so, it's probably possible. You have to sniff the network traffic and take a look using a tool like [Charles Proxy](https://www.charlesproxy.com). Please create a pull request with documentation if you find something interesting.
