### ISSUE TITLE
Well structured API documentation

### ISSUE THREAD

**Issue by scriptcoded** [svendahlstrand/ica-api#14]
While working on #13 I realized that the documentation is a little bit all over the place regarding style and syntax due to multiple contributors having added to the docs over the years. I was thinking of setting up a documentation page using [redoc](https://github.com/Redocly/redoc), and would just like to check with you first. Would you prefer to have it hosted on your GH Pages or something like that, or would you be OK with me hosting and keeping it up to date?

Thanks, and good job with the current docs!

**Comment by svendahlstrand** [comment]
When I started this reverse engineering effort, I had no idea the unofficial documentation would still be this popular eight years later. I'm glad it is, but I did make the classic mistake of not assigning a license to my work.

Now we are six contributors that collectively own the copyright to the documentation. To complicate things further, the work we've done together is the process of reverse engineering and documenting some else's API.

You have my blessing to build upon my work. I would appreciate credits and a link back to the original (this) project if you decide to do so. 😊

But do know that, from a strict legal perspective, you should probably get permission from all the contributors. That said, it would surprise me if anyone opposed your ReDoc idea.

Thanks for your kind words!
