### ISSUE TITLE
Add Item to shoppinglist

### ISSUE THREAD

**Issue by carlsall** [svendahlstrand/ica-api#15]
Thank you so much for this update !!!  Great job !!!
It works now but I can't find how to add an item to the shoppinglists.
Have I missed something?

**Comment by svendahlstrand** [comment]
I'm not using this API myself anymore, but you should be able to add items through [this endpoint](https://github.com/svendahlstrand/ica-api/blob/master/api-referens.md#post-apiuserofflineshoppinglistsofflineidsync).

**Comment by svendahlstrand** [comment]
Here's some Python code that makes use of that endpoint: [ica_shopping_list](https://github.com/kayjei/ica_shopping_list/blob/23e680b289631cf5ed4f907309dbdbe1bb9e934b/custom_components/ica_shopping_list/__init__.py#L161).

**Comment by carlsall** [comment]
Thanks!
Got it working  :-)
