### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by jonathanelmgren** [svendahlstrand/ica-api#18]
Hej! 

Relativt ny till rest apier och sitter med react & axios, när jag gör ett get anrop från min lokala server får jag CORS error type xhr.

Anropet fungerar fint med postman, vad kan jag göra?

**Comment by svendahlstrand** [comment]
Hej! Jag har inte undersökt vidare efter #16 men jag tror att ICAs servrar fortfarande inte är konfigurerade för [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Det betyder att du inte kan göra anropen från webbläsaren direkt till API:et. Du får i stället göra anropen från bakänden av applikationen – från Node.js eller motsvarande.
