### ISSUE TITLE
Skaffa AuthenticationTicket med python

### ISSUE THREAD

**Issue by Imlimp** [svendahlstrand/ica-api#19]
Hur gör man för att skaffa AuthenticationTicket med hjälp av reqests i python?

r = requests.get('https://handla.api.ica.se/api/login/', auth=('7001011234:567', ''))

Jag har kommit fram till att denna koden ger mig denna datan: 
`{
   "FirstName":"Hej",
   "LastName":"Då",
   "Ttl":9999,
   "CustomerRole":1,
   "Id":4839208493.0,
   "ZipCode":"43243",
   "City":"Any",
   "Gender":"Gender",
   "YearOfBirth":"9999",
   "CardType":0
}`

Men jag har inte tillgång till min AuthenticationTicket vad gör jag fel?

**Comment by svendahlstrand** [comment]
`AuthenticationTicket` leverereras som en HTTP header i svaret, så du behöver ta reda på hur du får fram dem i biblioteket du använder. Jag har begränsad erfarenhet av Python och ingen erfarenhet av Requests, men [enligt dokumentationen](https://docs.python-requests.org/en/latest/user/quickstart/) ser det ut som att du ska kunna skriva `r.headers` för att få en dictionary med alla headers.

**Comment by Imlimp** [comment]
Ah okej tack så jättemycket för snabbt svar och för en trevligt api!
