### ISSUE TITLE
curl : "Det går inte att logga in just nu. Försök lite senare."

### ISSUE THREAD

**Issue by tniclas** [svendahlstrand/ica-api#20]
Verkar inte kunna få en autentithication ticket numera. Är dettta API't inte aktuellt längre?

**Comment by svendahlstrand** [comment]
Förhoppningsvis var det precis som det stod, att ICA hade tillfälliga inloggningsproblem. Jag testade precis nu och det fungerade fint, fick en biljett och kunde göra ytterligare anrop. Håller tummarna för att det fungerar för dig också nu. 😊

**Comment by tniclas** [comment]
Det verkade var fel i min kod i slutändan faktiskt, funkar nu :)
Tack för svar och API't!

**Comment by ntullgren** [comment]
Någon mer som har märkt att "SessionTicket":en man får tillbaka när man anropar /api/login är "iOS is crap"? är detta nytt? XD
