### ISSUE TITLE
410 Unauthorized - Spärrat konto

### ISSUE THREAD

**Issue by jonathanelmgren** [svendahlstrand/ica-api#21]
![image](https://user-images.githubusercontent.com/81702447/148217005-c64051be-de41-40d8-a126-65b0cd119f27.png)

🙃, vet du vilken avdelning som skall kontaktas?

Har provat både ICA Banken och ICA Handla för att hitta Glömt Lösenord-knappen men på ICA Banken är det ett 4-siffrigt lösenord och ICA Handla får jag endast fel lösenord.

Kundtjänst kunde inte hjälpa till 🤔

**Comment by svendahlstrand** [comment]
Hehe, ingen aning tyvärr. Men oavsett vem du kontaktar bör du ju undvika att nämna att du använder deras interna API och att det inte fungerar för dig. 😅

Det är appen som heter *ICA – recept och erbjudanden* som jag demonterat och dokumenterat API:et på en gång i tiden. Jag misstänker att du inte heller kan logga in i appen som vanligt? Det bör ligga i ICAs intresse att du kan logga in i och använda deras app, så prova att helt enkelt [kontakta deras kundservice](https://www.ica.se/kundservice/). Lycka till!

**Comment by jonathanelmgren** [comment]
Det är väl det som är problemet, jag kan logga in överallt 🙃 Får försöka igen ohc hoppas på en annan kundtjänstmedarbetare

**Comment by JoniThornander** [comment]
Jobbar själv på ICA och kan säga att när det kommer till tekniska problem suger dom 😑. Ett tips är att gå till ditt närmaste ICA och be dom ringa butiksupport, då slipper du telefonkö och de kan skapa ett ärende åt dig.

Btw, ICA vet mycket väl om att folk använder deras API 😅

**Comment by jonathanelmgren** [comment]
Tack @JonathanThornander 

Lyckades få en 200. Däremot ingen AuthTicket.

Provade med detta (6 siffriga)-lösenord i appen också och kommer in utan konstigheter där.

![image](https://user-images.githubusercontent.com/81702447/148416661-eef513be-172d-4f1d-ae9b-043781cfc8a6.png)

**Comment by svendahlstrand** [comment]
Woohoo! 🎉 Vet inte vad det är för program du använder, men din biljett bör ligga under rubriken Header.
