### ISSUE TITLE
Lagligt sätt att läsa Icas, Hemköps, Coops, Willys (etc) produktkatalog programmatiskt?

### ISSUE THREAD

**Issue by ItsCubeTime** [svendahlstrand/ica-api#22]
Hej, jag funderar på att starta en liten webbsida för att jämföra matpriser på affärer såsom ovannämnda - därför kommer jag (antagningsvis) behöva kunna serialisera data om deras varor på en privatserver, har aldrig gjort "batchläsning"/"batch read" av webbsidor tidigare, undrar över vad ni skulle kunna rekommendera för strategi.

Är mitt bästa alternativ att läsa html element?

Är den äns lagligt att skanna av stora webbsidor eller kommer jag behöva deras tillåtelse?

**Comment by JoniThornander** [comment]
Intressant idé! De flesta lär ha regler angående web-scraping så jag skulle nog kolla upp det innan.

**Comment by svendahlstrand** [comment]
Jag är ingen jurist men generellt brukar företag hålla ganska hårt i sin data. 😄 Och troligtvis kan ICA hävda [upphovsrätt och/eller databasrätt](https://europa.eu/youreurope/business/running-business/intellectual-property/database-protection/index_sv.htm) för att stoppa dig. Speciellt om du gör den lilla webbsidan publik och får för dig att tjäna pengar på den.

Om inte annat bryter du säkert mot deras användaravtal. Gissar jag, utan att ha läst det.

Men om du håller den lilla webbsidan för dig själv och inte hamrar sönder deras webbservrar har jag svårt att tro att de kommer bry sig eller ens märka något.

Du skulle ju kunna höra efter med skaparna bakom [Matpriskollen](https://web.matpriskollen.se/startsida), [matspar.se](https://www.matspar.se/start) eller någon av de andra prisjämförelsetjänsterna hur de hämtar in sina priser?
