### ISSUE TITLE
Hämta saldo på ICA kort

### ISSUE THREAD

**Issue by pakerfeldt** [svendahlstrand/ica-api#23]
Har du någon idé om vilken endpoint som kan användas för att hämta saldot på ICA-kortet? Eller om du kan beskriva litegrann hur du har lyssnat på API-anropen så kanske jag kan gräva fram det själv.

Tack!

**Comment by svendahlstrand** [comment]
Det har jag tyvärr inte. 😢 Det är många år sedan jag använde API:et.

För att sniffa trafiken själv sätter du upp en proxy mellan appen och ICA:s servrar. Och använder helt enkelt appen som vanligt: titta saldot, i ditt fall. Sen är det bara att kika i proxyns loggar för att se hur anropen gick till.

Det är inte direkt purfärskt men blogginlägget [Monitoring iOS HTTPS Network Traffic](https://medium.com/@jamesmarino/monitoring-ios-https-network-traffic-a5d9fbe0edfe) beskriver ganska exakt mitt tillvägagångssätt med Charles. [Proxyman](https://proxyman.io/ios) och [mitmproxy](https://mitmproxy.org) är två alternativ.

**Comment by pakerfeldt** [comment]
Alright, for the record, endpointen är tydligen
```
api/user/cardaccountswithbalance?version=2
```
