### ISSUE TITLE
En Önskan

### ISSUE THREAD

**Issue by PierreGodetobii** [svendahlstrand/ica-api#24]
Inte en issue men en request, eller snarare önskan.
Jag och min fru har en magic mirror hemma https://magicmirror.builders/ 
där presenteras massa info som familjekalender,väder,kommande tv serier. m.m
jag kan knappt java så att bygga en modul är svårt för mig. 
här är exempel på moduler https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules
och en som vi använder tex https://github.com/boghammar/MMM-SL-PublicTransport/blob/master/MMM-SL-PublicTransport.js

kollade på API och såg flera saker som var intressanta för oss att se, 
1 inköpslistor
2 Erbjudanden
3 Strekkodssökning

I alla fall. detta är bara en önskan stäng ärendet om det känns ointressant/orelevant.

har ni frågor så nås jag på pierre@gode.one
Mvh  Pierre Gode

**Comment by svendahlstrand** [comment]
Hej Pierre! Riktigt kul idé, tycker jag, men som du själv är inne på ligger det utanför det här projektets ramar. Men jag såg att MagicMirror-forumet har [en avdelning för önskemål](https://forum.magicmirror.builders/category/9/requests) så där hade jag postat idén om en ICA-modul om jag var du. Förhoppningsvis får du napp. 😊

**Comment by PierreGodetobii** [comment]
Tack. såg även detta i en gammal issue. om saldo. kan du lägga till api/user/cardaccountswithbalance?version=2 i dokuentationen? 
mvh Pierre

**Comment by svendahlstrand** [comment]
Jag kan tyvärr inte avsätta tid till det just nu men om du eller någon annan lägger upp en pull request med ändringarna så drar jag mer än gärna in dem.

**Comment by PierreGode** [comment]
Yes, testar dom först, återkommer med en request. jag har börjat bygga jag har bara visuellt saldo på spegeln nu. 
jag kommer att referera till din api från min sida https://github.com/PierreGode/MMM-ICA

men denna är långt ifrån klar. började för 6 timmar sen.. men gör den publik när den är har all api implementerad.
![icasaldo](https://user-images.githubusercontent.com/8579922/223151666-2ea18e1c-9a97-4e49-9411-2a07803336b5.png)
