### ISSUE TITLE
curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by ztark12** [svendahlstrand/ica-api#25]
Får error "curl: (56) Recv failure: Connection reset by peer" när jag försöker göra anrop "curl -i -u 'username':'password' https://handla.api.ica.se/api/login/" i terminalen. Får också felmeddelande "Error: read ECONNRESET" när jag testar via Postman. Vad kan detta bero på?

**Comment by svendahlstrand** [comment]
Det är svårt att säga varför det händer men av någon anledning stänger ICA:s server ner anslutningen. Det skulle, till exempel, kunna vara så att servern har mycket att göra just nu och helt enkelt släpper anslutningen. Eller så har de ändrat något i sitt upplägg, t.ex. att API:et flyttat till en annan domän eller liknade.

Antingen får du vänta och försöka igen senare eller sniffa trafiken mellan ICA:s app och server för att lista ut om något ändrats för anropen.

**Comment by jula420** [comment]
Samma problem, dom måste ändrat.
