### ISSUE TITLE
Bilder från "ImageId"

### ISSUE THREAD

**Issue by erichall** [svendahlstrand/ica-api#4]
Hej!

Hur kan jag få bilderna utifrån ImageId som varje recept verkar returnera? Exempelvis "ImageId":160443.

Eric

**Comment by svendahlstrand** [comment]
Hej @erichall!

Tyvärr vet jag inte hur det går till. Jag satt och dokumenterade de bitarna av APIet jag var intresserad av, men det är fyra år sedan nu. Bilder grejade jag aldrig med.

Men det går säker att ta reda på! :smile: Jag använde [Charles][1] för att lyssna på trafiken mellan ICAs app på telefonen och den bakomliggande webbtjänsten. Om du gör det samma och besöker en vy i appen där en bild laddas ner så kan du förmodligen lista ut hur det hänger ihop därifrån.

Jag håller tummarna för att du hittar det du behöver och blir så klart glad om du vill komplettera dokumentationen med en "ryckbegäran" i så fall. 😉 

[1]: https://www.charlesproxy.com

**Comment by mjonssonme** [comment]
Började precis labba lite med detta. Bild URL verkar följa detta mönster.
`https://www.ica.se/ImageVault/Images/id_160443/width_770/aspectRatio_0.000000/ImageVaultHandler.aspx` när det gäller receptbilder. Så ersätt "160443" med annat ImageId och 770 med den bredd du behöver.
