### ISSUE TITLE
Lägga till saker i shopingkorg

### ISSUE THREAD

**Issue by ludvigaldrin** [svendahlstrand/ica-api#5]
Hej!
har någon av er lyckats med att lägga till saker i en shopingkorg? Har försökt med lite PUT kommandon men får det inte att fungera som jag önskar. Hade ju varit så smutt om man kunde lägga till för då kan man programmera en knapp vid tvättmaskinen som automatiskt pushar upp tvättmedel i ICA-korgen. Kan inte hitta någonstans och lyckas inte lösa det.

**Comment by svendahlstrand** [comment]
Hej @ludvigaldrin 

Jag har inte dragit in de här i `master` än, men ta en titt här: https://github.com/svendahlstrand/ica-api/pull/6/files
