### ISSUE TITLE
Is it possible to get the ingredients of individual items?

### ISSUE THREAD

**Issue by razvanilin** [svendahlstrand/ica-api#7]
Hej,
I want to get the ingredients of individual items without having to find a recipe first. Does the API allow it?
In the ideal scenario, it will be nice to get the ingredients of items identity through a code using this endpoint: `/api/upclookup?upc=7310390001383`.

Or is there another point that I can use to achieve this?

Many thanks!

**Comment by svendahlstrand** [comment]
Hej, @razvanilin, and sorry for my late reply. No, I don't think that kind of information is present in the API unfortunately. You could dig around for yourself tough – maybe you'll find something of interest. I used https://www.charlesproxy.com to sniff the traffic between the iOS app and the API. https://mitmproxy.org is a free and open-source alternative.
