### ISSUE TITLE
Klimat-API

### ISSUE THREAD

**Issue by PierreMesure** [svendahlstrand/ica-api#9]
Hej,

Tack så mycket för hela arbetet!

Jag undrar om ni har redan lyckats att hitta de klimatrelaterade APIer med adressen `handla.api.ica.se`.

Jag kan se de här endpoints när jag kolla sidan "Min Klimatmål" på [ica.se/klimat/mitt-klimatmal/](https://www.ica.se/klimat/mitt-klimatmal/):
```
/api/climateimprint/lastmonth
/api/climateimprint/history/ratio
/api/climateimprint/exchange
/api/climateimprint/welcomepage/:userid
/api/climateimprint/co2info
/api/climateimprint/calender
/api/climateimprint/recipe
/api/climateimprint/lastmonth/articlegroup
/api/climateimprint/moretips
/api/climateimprint/history
```

Finns det ett sätt att authentifiera sig på `ica.se` också? Just nu hittar jag inte hur man får den Cookie som används som token.

Men jag letar fortfarande efter ett sätt att använda dem programmatiskt.

**Comment by svendahlstrand** [comment]
Hey, and thanks. No, I have not stumbled over those endpoints in the app API. I can't find the feature in the app either, is it hiding there somewhere?

I have never tried authenticating against `ica.se` programmatically, but I'm sure it is possible. You will have to simulate an ordinary website login by looking at the traffic in the developer console and replicating that from your code. You will most definitely have to use cookies. 🍪Yummy!

I would start by opening `https://www.ica.se/logga-in/sso` in my browser and watch the traffic during my login. To make the same request using `curl` and keep the cookies around you could do this:

```
 curl --include --location --cookie cookie.txt --cookie-jar cookie.txt https://www.ica.se/logga-in/sso
```

If you are thinking about integrating this into a commercial product you should probably talk to ICA Sverige AB, though, and not just scrape the content. Just saying. 😅 (Regarding https://github.com/tmrowco/tmrowapp-contrib/issues/73.)
